### ISSUE TITLE
Devlink

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/open-dollar-app#1]
Get working with devlink

**Comment by alekseevaiana** [comment]
## Difficulties to run a project
- what is `YOUR_INFURA_KEY` which I have to use in `.env.development.local` file?
- is tailwindcss has this version on purpose? Can I remove it and add the latest?

## Steps to install devlink 
- Add `.webflowrc.js` file with this code:
```js
module.exports = {
    host: "https://api.webflow.com",
    rootDir: "./devlink",
    siteId: "64ac4f0e4fd899bd9c0009aa",
    authToken: process.env.WF_AUTH_TOKEN, // An environment variable is recommended for this field.
    cssModules: true,
};
```
- Add file `.env` with `WF_AUTH_TOKEN` (ask about  access token Sasha or Iana)
- `npm i @webflow/webflow-cli` to install webflow cli
- To sync Webflow components into the project run `npx webflow devlink sync`
