### ISSUE TITLE
Clone the reflexer docs

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/open-dollar-app#18]
- Create a new site for Open Dollar docs using a clone of https://docs.reflexer.finance/
- Update the index.html, title, headings, etc, to reflect the name Open Dollar
- Deploy using github pages to https://docs.opendollar.com

**Comment by alekseevaiana** [comment]
# Plan
1. Create a new site using https://docusaurus.io/docs/installation
2. Update names to Open Dollar
3. Copy content of https://docs.reflexer.finance/ ?
4. Create account on Versel and see keyp deployment configuration to deploy it the same way

**Comment by pi0neerpat** [comment]
Done!
