### ISSUE TITLE
Data fetching

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/open-dollar-app#6]
This is more of a research issue. Lets determine where each of these pieces of data is fetched- either directly from the contract, hardcoded in the asset config file (see #4)  or via API. From there we can determine what changes we will need to make

- [ ] Asset Price (OSM)
- [ ] Total Liquidation Penaltly
- [ ] Stability Fee 
- [ ] HAI Redemption Price
- [ ] Liquidation Price

![image](https://github.com/UseKeyp/open-dollar-app/assets/35622595/ac8b2b5b-24c2-47d0-834b-20fcd14c0677)

**Comment by jahabeebs** [comment]
@pi0neerpat 
1) Asset Price (OSM): The name and contract addresses of the assets come from here in the sdk: https://github.com/hai-on-op/sdk/blob/dev/src/contracts/addreses.ts the API call to get the price happens in the fetchFiatPrice function in api.ts. That result is persisted in the useGeb hook which is used to fetch and persist data from the SDK
2) Total Liquidation Penalty: fetchLiquidationData in virtualLiquidationData.ts fetches this info from the batch contract constructor and the result is persisted in useGeb as in # 1 of this list. 
3) Stability Fee: same as # 2
4) HAI Redemption Price: same as # 2
5) Liquidation Price: basically same as # 2--we could also use the SDK's liquidationPrice() function in the sdk: https://github.com/hai-on-op/sdk/blob/a8300a94a1fde4d65bcc75ae7df626ed8fbdfe19/src/schema/safe.ts#L73. VirtualLiquidationData.sol explains that the CRatio is used to calculate the liquidation price

**Comment by pi0neerpat** [comment]
Done!
